export const theme = {
  colors: {
    bg: '#F0F4FF',
    surface: '#FFFFFF',
    surfaceAlt: '#E8EEFF',
    overlay: 'rgba(255,255,255,0.85)',
    primary: '#5B5FEF',
    primaryLight: '#7B7FF5',
    primaryDark: '#3F43CC',
    accent: '#12C2E9',
    success: '#10B981',
    danger: '#EF4444',
    warning: '#F59E0B',
    deber: '#5B5FEF',
    taller: '#12C2E9',
    prueba: '#EF4444',
    reunion: '#10B981',
    text: '#1E1E2E',
    textMid: '#4A4A6A',
    textMuted: '#9090B0',
    border: '#DDE3FF',
    inputBg: '#F7F8FF',
    google: '#FFFFFF',
    white: '#FFFFFF',
  },
  radius: {
    sm: 8,
    md: 14,
    lg: 20,
    xl: 28,
  },
  shadow: {
    card: {
      shadowColor: '#5B5FEF',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.10,
      shadowRadius: 16,
      elevation: 6,
    },
    fab: {
      shadowColor: '#5B5FEF',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.30,
      shadowRadius: 20,
      elevation: 16,
    },
  },
} as const;
